### ISSUE TITLE
Image inserting does nothing

### ISSUE THREAD

**Issue by krsyoung** [Nerian/bootstrap-wysihtml5-rails#100]
Hey,

I'm currently unable to insert image links.  I've tried using both the latest stable gem as well as from master.  When trying to add an image it properly displays the pop-up window but the resulting HTML inserted always looks like this:

``` html
<img alt="" title="Image: null">
```

If I manually modify the form HTML by adding `data-wysihtml5-dialog-field="src"` things work as expected:

``` html
<input value="http://" data-wysihtml5-dialog-field="src" class="bootstrap-wysihtml5-insert-image-url form-control">
```

I think I'm facing an issue that has been fixed here: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues/94 (milestone 0.3.4).

Is this just a matter of waiting for this project to sync with the upstream bootstrap3-wysiwyg?  Any suggestions on patching / working around in the meantime? 

Thanks!

**Comment by ryan2johnson9** [comment]
thanks @bleakwood. Sorry to bother, I have the gem version 0.3.3.2 and this error still occurs. Are we waiting for a future version?

**Comment by Nerian** [comment]
No new version for https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg. 

So I am going to release a new version with the changes @bleakwood suggested.

https://github.com/Nerian/bootstrap-wysihtml5-rails/commit/bf4a874b7bde38c7e3ce8425115fb809617e5777

Version 0.3.3.3 is up. Let me know if this fixes it.

**Comment by ryan2johnson9** [comment]
Thanks @Nerian editing link issue still exists with 0.3.3.3, so I am sticking with @bleakwood's fix.
