### ISSUE TITLE
icons not appearing while using with font awesome

### ISSUE THREAD

**Issue by ckgagan** [Nerian/bootstrap-wysihtml5-rails#105]
The indentation icons are not appearing while using fontowesome. It would be nice if this library can use font awesome icons.

**Comment by zedtux** [comment]
It would be nice to update the `README.md` with this information

**Comment by Nerian** [comment]
@zedtux Good idea. Want to make the Pull Request?

**Comment by zedtux** [comment]
@Nerian done ! :)

**Comment by ckgagan** [comment]
:+1:
