### ISSUE TITLE
 The given range and the current selection belong to two different document fragments

### ISSUE THREAD

**Issue by cmcguff** [Nerian/bootstrap-wysihtml5-rails#111]
I'm seeing this error pretty consistently - really not sure what is driving this,
begin reported from b.addRange(l) in bootstrap3-wysihtml5.js

I am using the latest version (0.3.3.2), I have updated my bootstrap to 3.3.2 as well in case that was the issue, but still seeing the problem. Do you have any ideas what might be happening here?

**Comment by theonegri** [comment]
I too have the issue.
@Nerian any idea what would be the issue?

**Comment by theonegri** [comment]
I too have the issue.
@Nerian any idea what would be the issue?

**Comment by Nerian** [comment]
Hi,

Please send issues with bootstrap-wysihtml5 to this repo: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg
