### ISSUE TITLE
Individual files for finetuning doesn't exist

### ISSUE THREAD

**Issue by constantm** [Nerian/bootstrap-wysihtml5-rails#114]
As per the docs, you can do the following:

```
//= require bootstrap-wysihtml5/wysihtml5x-toolbar.js
//= require bootstrap-wysihtml5/handlebars.runtime.min.js
//= require bootstrap-wysihtml5/minimum
```

Those files exist in the repository, but not in the gem. So, to do the above, you need to add the git repo to your Gemfile instead of just using the gem. Need to either update docs or gem.

**Comment by Nerian** [comment]
Hi,

Yes, I was waiting for this PR to be made again before publishing the new gem: https://github.com/Nerian/bootstrap-wysihtml5-rails/pull/112

**Comment by constantm** [comment]
Ah okay great! Thanks.

**Comment by Nerian** [comment]
Nonetheless, let's publish a new version. If people are interested in the color css we can add it again

**Comment by Nerian** [comment]
version 0.3.3.5 is published

**Comment by Nerian** [comment]
version 0.3.3.6 is published, with a fix for the colors too.

**Comment by constantm** [comment]
👍
