### ISSUE TITLE
All my wysihtml5 are 100% height

### ISSUE THREAD

**Issue by arthurtalkgoal** [Nerian/bootstrap-wysihtml5-rails#115]
Hi,

I found my original textarea height is irrelevant to the wysihtml5.

All editor turns to 100%.

How to set height to auto or pass as parameters?

**Comment by Nerian** [comment]
Hi,

As far as I know, it should be using the textarea's height.

**Comment by Nerian** [comment]
That's the behavior I see in the test app: https://github.com/Nerian/bootstrap-wysihtml5-rails/tree/master/testapp

**Comment by Ripsnorta** [comment]
If you are using simple_form_for, you can set the height of the textarea by:

> <%= f.input :post_content, :as => :text, input_html: { class: 'wysihtml5', **style: 'height:350px'** } %>
