### ISSUE TITLE
toolbar options

### ISSUE THREAD

**Issue by miggy** [Nerian/bootstrap-wysihtml5-rails#119]
including either "link" or "blockquote" (also "fa") to toolbar options hash causes error

**Comment by Nerian** [comment]
https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg#buttons

**Comment by miggy** [comment]
I am pretty sure I placed in the options correctly.  Please see below. If I leave out the "link" and "blockquote" options, all is well.  When they are in, throws a "unexpected ," error.  

Am I missing something super obvious?  Thanks for your help.

  $('.wysihtml5').each (i, element) ->
    $(element).wysihtml5 toolbar:
    	"font-styles": false,
    	"emphasis": true,
    	"lists": true,
    	"html": false,
    	"image": false,
    	"color": false,
    	"size": 'xs',
      'link': true,
      'blockquote': true

**Comment by Nerian** [comment]
Your code fine to me, though I don't use coffescript.

I used the test app (https://github.com/Nerian/bootstrap-wysihtml5-rails/tree/master/testapp) and used this code:
```html
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<textarea class="textarea" placeholder="Enter text ..." style='width: 100%;height: 300px'></textarea>

<script type="text/javascript">
  $('.textarea').wysihtml5({
    toolbar: {  "font-styles": false,
      "emphasis": true,
      "lists": true,
      "html": false,
      "image": false,
      "color": false,
      "size": 'xs',
      'link': true,
      'blockquote': true }
    }
  );

</script>
```

It didn't raise any errors.

**Comment by Nerian** [comment]
Closing due inactivity. Please reopen if you still have the issue.
