### ISSUE TITLE
Problems with require bootstrap-wysihtml5/locales/es-ES

### ISSUE THREAD

**Issue by lcamach** [Nerian/bootstrap-wysihtml5-rails#122]
I trying use Spanish locale but this appear (Uncaught TypeError: Cannot read property 'locale' of undefined) when I adding this line //= require bootstrap-wysihtml5/locales/es-ES to application.js

**Comment by Nerian** [comment]
Full backtrace pls :)

**Comment by lcamach** [comment]
This is my application.js

```
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or vendor/assets/javascripts of plugins, if any, can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/sstephenson/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require bootstrap-wysihtml5/locales/es-ES
//= require bootstrap-wysihtml5
//= require jquery_nested_form
//= require chosen-jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require_tree .
//

```
And I only can see the error in developer tool of my browser. And this is the screenshot

![screen shot 2015-05-06 at 3 00 32 pm](https://cloud.githubusercontent.com/assets/5016854/7502331/e6fc959c-f400-11e4-89a4-2866dcc46b85.png)

**Comment by Nerian** [comment]
Switch the requires order. Need to be like this:

//= require bootstrap-wysihtml5
//= require bootstrap-wysihtml5/locales/es-ES

**Comment by lcamach** [comment]
Ups!! Thank you so much! :)

**Comment by Nerian** [comment]
No problem
