### ISSUE TITLE
broken tags

### ISSUE THREAD

**Issue by ana-ines** [Nerian/bootstrap-wysihtml5-rails#123]
Hello, i'm opening this issue because i'm using this gem in my project where i am editing letters and certificates, and then exporting them to pdf.

The problem is when i put some style into the text. In the editor i see it perfect, but when i export to pdf, the pdf shows the tags brokens.. for example: "p style="text-align: left;">Señor Presidente del Colegio de Abogados:/p>p>" .

why it should be ?
thanks a lot!.

**Comment by Nerian** [comment]
Hi,

How are you exporting to pdf? Code sample would be nice.
