### ISSUE TITLE
Can't start wysihtml5 plugin

### ISSUE THREAD

**Issue by dapi** [Nerian/bootstrap-wysihtml5-rails#128]
Hi, Herian!

Thank you for the gem )

I have problem - can't start the plugin:

Here is dump from Safari console

```
> $('#category_description').length
< 1

> $('#category_description').wysihtml5();
< TypeError: undefined is not a function (evaluating '$('#category_description').wysihtml5()')

> wysihtml5
< Object
```

I've tried to require JS as:

`= require bootstrap-wysihtml5`
and
`= require bootstrap-wysihtml5/index`

**Comment by Nerian** [comment]
looks good :)

Maybe restart app?

**Comment by dapi** [comment]
Have tried )

**Comment by Nerian** [comment]
In JS it would be //= require bootstrap-wysihtml5, or are you using Coffe script?

**Comment by dapi** [comment]
Yes, coffee )

Where is there place wysihtml5 defines? I'll try to debug it

**Comment by dapi** [comment]
I'have tried to start it directly:
```
new wysihtml5.Editor 'category_description'
```

works fine

**Comment by Nerian** [comment]
Weird :)

https://github.com/Nerian/bootstrap-wysihtml5-rails/blob/master/vendor/assets/javascripts/bootstrap-wysihtml5/bootstrap3-wysihtml5.js#L185

There is a test app: https://github.com/Nerian/bootstrap-wysihtml5-rails/tree/master/testapp

Take a look and see if there is something different from what you have.

**Comment by dapi** [comment]
Found.

The bug was in another requirements that overloads jQuery.

Nerian, thank you very much for such quick responses!
