### ISSUE TITLE
Block code and Image links are not working as expected

### ISSUE THREAD

**Issue by dilnavaz** [Nerian/bootstrap-wysihtml5-rails#129]
Hi,
When I try to turn off the block code after typing some text, it turns off the blockcode on the text I typed in. 
Also the image link is not working. It only inserts a new "img" tag, but nothing inside it.

Any solutions?

**Comment by Nerian** [comment]
Hi,

Yes, I can reproduce those issues. There is nothing I can do about it, as I only package the project in a ruby gem. Feel free to raise an issue in the original project: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg. Although is kind of inactive.

Personally, I switched to summernote in my projects: 

* http://summernote.org/#/
* https://github.com/summernote/summernote-rails
