### ISSUE TITLE
why my editor look like this ?

### ISSUE THREAD

**Issue by mirzalazuardi** [Nerian/bootstrap-wysihtml5-rails#130]
why my editor look like this ?
![weird](http://imagebin.ca/277VAMhasXO2/ScreenShot2015-07-01at5.14.58PM.png)

its weird

**Comment by Nerian** [comment]
Looks like you are missing icons. Check that you have bootstrap installed and it includes the icons.

**Comment by mirzalazuardi** [comment]
yes i think it so, but after several attempts, looking for answer googled. it's still not work.
I'm using rails 4

![condition](http://filebin.ca/27E4SYp28fZ4/ScreenShot2015-07-02at3.42.59PM.png)

any suggestion @Nerian

**Comment by Nerian** [comment]
Are you missing the icons just on the editor, or does them work elsewhere?

**Comment by mirzalazuardi** [comment]
i think it because my assets configuration on rails. thanks for the attention.

**Comment by hecontreraso** [comment]
@mirzalazuardi  how did you  solve it?
