### ISSUE TITLE
Can't Expand Text Area

### ISSUE THREAD

**Issue by HunterMeyer** [Nerian/bootstrap-wysihtml5-rails#137]
Text areas typically have a sizing toggle in the lower-right corner. Like the GitHub text area:
<img width="676" alt="screen shot 2015-09-12 at 11 42 18 pm" src="https://cloud.githubusercontent.com/assets/4690516/9835118/ffbbd9a0-59a7-11e5-859e-18215495a629.png">

The WYSIHTML5 editor doesn't seem to have this feature. Is there a way to enable it?
<img width="687" alt="screen shot 2015-09-12 at 11 44 01 pm" src="https://cloud.githubusercontent.com/assets/4690516/9835127/4cd8b71c-59a8-11e5-8a25-e1836f19d7fc.png">

**Comment by Nerian** [comment]
Hi,

I am not sure, sorry :)

I just packaged this project into a gem; I don't maintain it. You may want to ask here https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg.

Personally, I think this project is a little bit stale. It hasn't been updated in half a year. And the last commit in the wysihtml project is from 18 Dec 2014. 

I switched to use this one in my projects: http://summernote.org. It does allow manual resizing, as well as doing it automatically as you write.

There is a summernote-rails gem.

**Comment by n1ckbren** [comment]
Maybe will be useful ¯ \ _ (ツ) _ / ¯
``` scss
iframe {
  &.wysihtml5-sandbox {
    resize: vertical;
  }
}
```
