### ISSUE TITLE
Uncaught TypeError: Handlebars.compile is not a function

### ISSUE THREAD

**Issue by ChrisEstanol** [Nerian/bootstrap-wysihtml5-rails#138]
I am working with Spree commerce and use bootstrap-wysihtml5-rails to format product text.
When I `//= require bootstrap-wysihtml5` in my js I get this error: 
`Uncaught TypeError: Handlebars.compile is not a function`
Which also disable all ajax functionalities.
If I remove the `//=require...` it works again.
I have attempted to use `//= require bootstrap-wysihtml5/minimum`
And get the following error:
`ActionView::Template::Error (couldn't find file 'bootstrap-wysihtml5/wysihtml5x-toolbar' with type 'application/javascript'):`
Any idea how I could solve this?

**Comment by vernondegoede** [comment]
I'm having exactly the same issue. Did you manage to solve this?

**Comment by ChrisEstanol** [comment]
Nope, just removed bootstrap-wysihtml5 for now.

**Comment by vernondegoede** [comment]
We used Bootsy for our text editor, which used bootstrap-wysihtml5 as a rich text editor. It seemed this plugin was using Handlebars as well, which conflicted with Handlebars in Spree (they use it for building the taxon tree in the backend).

I resolved this issue by changing the order in which spree/backend and bootsy were included in the backend.

**Comment by ChrisEstanol** [comment]
Thanks for the info. And I didn't know bootsy, it looks like a nice and easy way to plug a text editor to rails.
