### ISSUE TITLE
wysihtml not activating unless you refresh browser

### ISSUE THREAD

**Issue by mrdinghy** [Nerian/bootstrap-wysihtml5-rails#139]
So i installed everything and calling the wsyi with simple_form method and the initial load does not display the toolbar or show the text with formatting (it displays raw, with HTML tags). All i have to do is refresh the browser and they appear. 

Any clues why this happens...?
thanks

**Comment by Nerian** [comment]
Hi,

That's a weird one. So you load the page and it doesn't work, but subsequent loads do work?

**Comment by mrdinghy** [comment]
yeah.... but actually on a simpler install its fine.... can't isolate the difference issue

**Comment by paa001** [comment]
This is similar to the problem with the Turbolinks

**Comment by apdarr** [comment]
I've experienced this same issue. I had to remove Turbolinks from my Gemfile to have the assets load without manually refreshing the page. However, this seems like a suboptimal solution. 

Any idea on why this is happening? Please feel free to re-open this issue!
