### ISSUE TITLE
Simple form option not working

### ISSUE THREAD

**Issue by Uysim** [Nerian/bootstrap-wysihtml5-rails#140]
In simple form I do 
= f.input :description, as: :wysihtml5, wysihtml5: { html: true }, input_html: { class: 'form-control', rows: '30' },

but it did not work

**Comment by Nerian** [comment]
What did not work? Error message?

**Comment by pekq** [comment]
Confirmed. You can't pass parameters for the script tag when using simple form.

`<%= f.input :description, as: :wysihtml5, wysihtml5: { locale: "es-ES" } %>`

Generates:

`<script type="text/javascript">$('textarea[id=product_description]').wysihtml5();</script>`

**Comment by otlaitil** [comment]
This issue relates to #105 which was fixed and merged to master. However the newest release (0.3.3.7) does not include this feature. @Nerian could you please make a new release?

**Comment by Nerian** [comment]
Sure thing, version 0.3.3.8 released :)

**Comment by Nerian** [comment]
I am closing this, let me know if you still have the issue after updating your gem.

**Comment by otlaitil** [comment]
Great, thanks @Nerian ! All good now, I tested it and the options are now being rendered correctly.

**Comment by Nerian** [comment]
:tada:

**Comment by trejo08** [comment]
Hi guys, I resolved this issue putting the options just like that:
<%= f.input :description, as: wysihtml5: {toolbar: { link: false, image: false, html: true}} %>

I hope it works for you.

Regards
