### ISSUE TITLE
Modal backdrop for link glitches often

### ISSUE THREAD

**Issue by skipperguy12** [Nerian/bootstrap-wysihtml5-rails#142]
I'm not sure if anyone's experienced this, but for my editor when the link-button is pressed often pressing cancel, inserting, editing an existing link, or some variation of these ultimately leads to the modal backdrop persisting. I tried doing some basic research, and I'm not totally sure if this is right, but apparently the modal backdrop issue is commonly caused by multiple modal instances not closing correctly.

**Comment by Nerian** [comment]
Hi,

You may want to ask here: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

**Comment by darmenise** [comment]
+1 happens to me too!
