### ISSUE TITLE
Problem with toolbar

### ISSUE THREAD

**Issue by Rubioli** [Nerian/bootstrap-wysihtml5-rails#143]
I am trying to remove link & image toolbar. When I try to add:
` $('.wysihtml5').wysihtml5({'toolbar': {'link': false, 'image': false}})`

The whole form "crashes" and text area doesn't shows (I am using simple_form_for).

How can I remove some toolbars?

**Comment by Nerian** [comment]
Try with `$('.wysihtml5').wysihtml5({ toolbar: { 'link': false, 'image': false } })`

**Comment by Rubioli** [comment]
It's not working.

This is how I added it (I am using Haml):

```
:javascript
  $('.wysihtml5').wysihtml5({ toolbar: { 'link': false, 'image': false } })
```

Any other solutions?

**Comment by Nerian** [comment]
Hi,

I ma not sure :)  What's the error message that you are getting? Can you confirm that it is creating a script tag?

**Comment by Rubioli** [comment]
Sure, What happens in after adding this line in my code, the form crash as the attachment file. Please see the attachment to see what I mean :)
![skjermbilde 2016-03-04 kl 10 30 08](https://cloud.githubusercontent.com/assets/16593596/13523178/1d87179a-e1f4-11e5-8a91-c19fe41f4259.png)

**Comment by Rubioli** [comment]
I fixed it by this solution:
`= f.input :description, input_html:{id: "description-textarea"}`

Javascript:
`$('#description-textarea').wysihtml5({ toolbar:{ "fa": true, "link": false, "image": false, "blockquote": false } });`

**Comment by Rubioli** [comment]
I fixed it by this solution:
`= f.input :description, input_html:{id: "description-textarea"}`

Javascript:
`$('#description-textarea').wysihtml5({ toolbar:{ "fa": true, "link": false, "image": false, "blockquote": false } });`

**Comment by trejo08** [comment]
Hi @Rubioli, I resolve this issue putting the options at simple_form input just like that:
<%= f.input :description, as: wysihtml5: {toolbar: { link: false, image: false}}   %>

regards.
