### ISSUE TITLE
Table command but no table template

### ISSUE THREAD

**Issue by mlaco** [Nerian/bootstrap-wysihtml5-rails#154]
I'm looking for a WYSIWYG editor with table support. Looking through the source code, I noticed that there are commands for tables in `vendor/assets/javascripts/bootstrap-wysihtml5/wysihtml5x-toolbar.js`, but there no template for tables in `vendor/assets/javascripts/bootstrap-wysihtml5/templates.js`. Do you know why this is? Did there used to be table support, or was it in development?

**Comment by Nerian** [comment]
Hi,

I am not sure sure if wysihtml5 supports table (I am not the creator, I just package it in a gem). I know that http://summernote.org/ does support tables and the editor works very well. There is a gem for rails too: https://github.com/summernote/summernote-rails
