### ISSUE TITLE
wysihtml5 issue when running on jQuery version 3

### ISSUE THREAD

**Issue by mcortes91** [Nerian/bootstrap-wysihtml5-rails#155]
Hello,

I am currently running Jquery version 3 on my machine. On my JS console, I am getting a warning that states, 'Use of Mutation Events is deprecated. Use MutationObserver instead'. 
I found the error is in the file, bootstrap-wysihtml5/wysihtml5x-toolbar.self-f835bfe0ef8681a04b930aafeb1f792406f9426924cc7d7bf8d08463415b8120.js?body=1 
and it is on lines 5747 and 5761. When can I expect this issue to be resolved?

Thanks.
![image](https://user-images.githubusercontent.com/12374332/28539180-cd41a9c4-707e-11e7-9869-d52fadc110e1.png)

**Comment by Nerian** [comment]
Hi,

You would have to inquire about it here: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg. I don't really maintain the code, I just package it into a gem.
