### ISSUE TITLE
Defer inline javascript execution in the simple_form input until after the document is ready

### ISSUE THREAD

**Issue by cheeseweasel** [Nerian/bootstrap-wysihtml5-rails#156]
If jQuery is loaded after the main content (`javascript_include_tag 'application'` just before the `</body>` for example), the editor will throw a javascript error and not initialise.

Something along these lines: https://stackoverflow.com/a/21814964/946270 would do the job. If I get a mo, I'll submit a PR.

**Comment by Nerian** [comment]
Sounds good. Feel free to submit a PR 👍

**Comment by Nerian** [comment]
A Pull Request that implements this very behavior has just been merged. Try master and see if it fixes your issue.
