### ISSUE TITLE
Add a link stuck in the background

### ISSUE THREAD

**Issue by kbaum** [Nerian/bootstrap-wysihtml5-rails#19]
My add a link modal is stuck in the background and when i click on it, it disappears.

https://skitch.com/karlbaum/eweda/3811-turtle-creek-blvd-21st-floor-suite-2100

Not sure if i am missing a js lib or maybe one of my existing libs is wrong version or conflicting.

thx!

**Comment by mamute** [comment]
I have this same problem... When I navigate inside the text with arrows keys and pass through a link, a modal is opened. If I click the close button, it work's, but if I click at Cancel or Insert Link the modal is closed, but background keep on the screen.

**Comment by grepruby** [comment]
@mamute , did you find any solution on this, I stuck on same.
