### ISSUE TITLE
Youtube embed links

### ISSUE THREAD

**Issue by bcackerman** [Nerian/bootstrap-wysihtml5-rails#47]
I can't paste an embed code into my editor.  I get a No Route Error.  Any ideas how to overcome this?

**Comment by kamok** [comment]
Hi Nerian, the jhollingworth wysihtml5 still hasn't merged the [pull request #163 for Inserting Youtube videos](https://github.com/jhollingworth/bootstrap-wysihtml5/pull/163). Which means that the functionality to do so isn't in this gem as of today. Am I correct in that statement?

**Comment by Nerian** [comment]
@kamok We are now using this fork: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg.
